# Default Configuration for AI Agent Framework

# LLM Configuration
llm:
  default_provider: "claude"
  temperature: 0.7
  max_tokens: 1000
  
  claude:
    model_name: "claude-3-7-sonnet-20250219"
    timeout: 30
    context_window: 200000

# Agent Configuration
agent:
  default_max_iterations: 10
  verbose: false
  include_timestamps: true
  system_prompt: "You are a helpful assistant that can use tools to accomplish tasks."

# Memory Configuration
memory:
  max_messages: 100
  include_system_messages: true
  
  # Vector memory configuration
  vector_memory:
    enabled: false
    embedder_type: "openai"
    vector_store_type: "faiss"
    search_k: 5
    use_for_conversation_history: false

# Vector Store Configuration
vector_store:
  default_type: "chroma" 
  embedding_type: "openai"
  persist_directory: "./data/vector_store"
  chunk_size: 1000
  chunk_overlap: 200
  
  # Text splitting defaults
  text_splitter:
    recursive_character:
      separators: ["\n\n", "\n", ". ", " ", ""]
    markdown:
      heading_boost: true
    html:
      strip_tags: true

# Tools Configuration
tools:
  enable_filesystem: false
  enable_web_access: false
  enable_knowledge_base: false
  enable_conversation_memory: false
  default_timeout: 5

  knowledge_base:
    path: "./data/knowledge_base"
    default_collection: "default"
    auto_chunk: true
    max_chunk_size: 1000

# Logging Configuration
logging:
  level: "INFO"
  console_level: "INFO"
  log_dir: "logs"
  max_file_size_mb: 10
  backup_count: 5

# Workflow Configuration
workflow:
  max_steps: 10
  record_inputs_outputs: true